### PR TITLE
Updated gradle and switch to support AlertDialog

### LINKED ISSUE #85: Use android.support.v7.app.AlertDialog instead of android.app.AlertDialog
Between honeycomb and lollipop, the `AlertDialog` will use the default theme instead of the `AppCompat` defined theme. It will basically fall back to Holo. It would be nice if the library was using `android.support.v7.app.AlertDialog` instead of `android.app.AlertDialog` and add a way to tweak the theme for all versions (it's currently locked for lollipop and above for some reason https://github.com/hotchemi/Android-Rate/blob/209f94717a8af7ed6d6095d5dfb32d27f5ec73ca/library/src/main/java/hotchemi/android/rate/Utils.java#L22)

### PR DESCRIPTION
**Pull request by mudar**
Fixes #85

### CODE REVIEW

**Comment by mudar** [comment]
It seems there's some configuration error with the Travis CI validation
```
error: device '(null)' not found
Failed to start emulator
The command "curl -L https://raw.githubusercontent.com/embarkmobile/android-sdk-installer/master/wait_for_emulator | bash" 
  failed and exited with 1 during Your build has been stopped.
Failed to Initialize backend EGL display
```

**Comment by hotchemi** [comment]
@mudar Thanks. Yeah...I'll fix it and merge later. Anyway thx!

**Comment by hotchemi** [comment]
@mudar Could you merge master? Sorry! After that, I'm gonna merge it.

**Comment by mudar** [comment]
@hotchemi I've rebased from your master branch. I had to resolve 2 small conflicts with `build.gradle`

**Comment by hotchemi** [comment]
Thx!

**Comment by hotchemi** [comment]
It causes some crashed https://github.com/hotchemi/Android-Rate/issues/98, https://github.com/hotchemi/Android-Rate/issues/99 so I'll revert it.

**Pull request merged**
