### PR TITLE
Option to show 'never' button or not

### PR DESCRIPTION
**Pull request by sandro-csimas**

### CODE REVIEW

**Comment by sandro-csimas** [comment]
#88

**Comment by hotchemi** [comment]
Thx man! Do you need it soon?

**Comment by sandro-csimas** [comment]
This issue is not so urgent to me, but once you have a time, please merge the branch. \o/

**Comment by hotchemi** [comment]
@sandro-csimas Thx, I'll release tomorrow(midnight in japan so:))!

**Pull request merged**
