### PR TITLE
add boolean to clearAgreeShowDialog

### PR DESCRIPTION
**Pull request by bblia**
I'm leveraging this lib after I show my own dialog on whether they're liking the app or not. Essentially need a way to set AgreeShowDialog for both cases -- if they hit no, never show the app rate dialog again.

### CODE REVIEW

**Comment by hotchemi** [comment]
Thx just a minute!

**Comment by hotchemi** [comment]
Thx!

**Comment by rogerhu** [comment]
+1 how do we get this pushed to maven central?

**Comment by hotchemi** [comment]
@bblia @rogerhu I'll publish new version in the evening. Stay tuned.

**Comment by bblia** [comment]
Thank you so much! :)

**Comment by hotchemi** [comment]
Sorry for the late. 0.5.4 will be out soon!

**Pull request merged**
