### PR TITLE
Added support for setting custom dialog style

### PR DESCRIPTION
**Pull request by swellner**
I have implemented a setting to support a custom dialog style. In my case i have a global style for textviews and this style overrides the style in the dialog.

### CODE REVIEW

**Comment by hotchemi** [comment]
I'll check it, thanks,

**Comment by hotchemi** [comment]
@swellner Could you merge master? Sorry! After that, I'm gonna merge it.

**Comment by mudar** [comment]
These changes are included in my PR. Sorry @swellner, I should have done a real merge to keep your commits history, but when I started I wasn't sure why the PR was pending, and I needed a quick solution for my project!

**Comment by hotchemi** [comment]
Ah sorry I was so busy to maintain other library... :sob: Really sorry @swellner !

**Pull request closed without merging**
